# Docker image for CI testing of the DEEPaaS API
# Note there is probably no gpu in the CI server
ARG tag=base
FROM ai4oshub/witoil-for-imagine:${tag}
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir tox
CMD ["sleep", "infinity"]